---
# =========================================================
# PACKAGE REPOSITORIES
# =========================================================

- name: Update package metadata
  ansible.builtin.dnf:
    update_cache: true

- name: Install DNF plugins
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present

- name: Enable CRB repository
  ansible.builtin.command:
    cmd: dnf config-manager --set-enabled crb
  changed_when: false

- name: Install EPEL repository
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: Refresh package metadata
  ansible.builtin.dnf:
    update_cache: true


# =========================================================
# BASE OS PACKAGES
# =========================================================

- name: Install common packages
  ansible.builtin.dnf:
    name: "{{ common_packages }}"
    state: present


# =========================================================
# KERNEL BASELINE
# =========================================================

- name: Update Rocky Linux kernel packages
  ansible.builtin.dnf:
    name:
      - kernel
      - kernel-core
      - kernel-modules
      - kernel-modules-extra
    state: latest
  register: bootstrap_kernel_update

- name: Reboot after kernel update
  ansible.builtin.reboot:
    msg: "Rebooting after Rocky Linux kernel update"
    reboot_timeout: 600
    connect_timeout: 10
    post_reboot_delay: 10
  when:
    - bootstrap_kernel_update.changed

- name: Refresh Ansible facts after reboot
  ansible.builtin.setup:
  when:
    - bootstrap_kernel_update.changed


# =========================================================
# QEMU GUEST AGENT
# =========================================================

- name: Check if QEMU guest agent device exists
  ansible.builtin.stat:
    path: /dev/virtio-ports/org.qemu.guest_agent.0
  register: qemu_ga_dev

- name: Enable QEMU guest agent
  ansible.builtin.service:
    name: qemu-guest-agent
    state: started
    enabled: true
  when:
    - qemu_ga_dev.stat.exists


# =========================================================
# TIMEZONE
# =========================================================

- name: Configure timezone
  ansible.builtin.file:
    src: /usr/share/zoneinfo/Asia/Phnom_Penh
    dest: /etc/localtime
    state: link
    force: true


# =========================================================
# SSH
# =========================================================

- name: Configure SSH hardening
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config.d/99-homelab.conf
    owner: root
    group: root
    mode: "0600"
    content: |
      PubkeyAuthentication yes
      PasswordAuthentication no
      KbdInteractiveAuthentication no
      PermitRootLogin no
      AllowUsers rocky
      X11Forwarding no
      MaxAuthTries 3
      LoginGraceTime 30
  notify: Restart sshd