---
# =========================================================
# K3S
# =========================================================

k3s_binary: "/usr/local/bin/k3s"
k3s_kubeconfig: "/etc/rancher/k3s/k3s.yaml"


# =========================================================
# HELM
# =========================================================

helm_binary: "/usr/local/bin/helm"
helm_version: "v3.22.0"

helm_install_url: "https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3"
helm_install_script: "/tmp/get-helm-3.sh"


# =========================================================
# CERT-MANAGER
# =========================================================

cert_manager_version: "v1.21.2"

cert_manager_namespace: "cert-manager"

cert_manager_chart: "oci://quay.io/jetstack/charts/cert-manager"

cert_manager_timeout: "10m"


# =========================================================
# RANCHER
# =========================================================

rancher_version: "2.15.1"

rancher_namespace: "cattle-system"

rancher_repo_name: "rancher-stable"
rancher_repo_url: "https://releases.rancher.com/server-charts/stable"

rancher_chart: "rancher-stable/rancher"

rancher_replicas: 1

rancher_timeout: "15m"


# =========================================================
# RANCHER HOSTNAME
# =========================================================

rancher_primary_server: "{{ groups['k3s_servers'][0] }}"

rancher_primary_ip: >-
  {{
    hostvars[rancher_primary_server].ansible_host
    | default(rancher_primary_server)
  }}

rancher_hostname: "{{ rancher_primary_ip }}.sslip.io"


# =========================================================
# INGRESS
# =========================================================

rancher_ingress_class: "traefik"