---
- name: Install primary K3s server
  hosts: "{{ groups['k3s_servers'][0] }}"
  become: true
  gather_facts: true

  roles:
    - k3s


- name: Join additional K3s servers
  hosts: "k3s_servers:!{{ groups['k3s_servers'][0] }}"
  serial: 1
  become: true
  gather_facts: true

  roles:
    - k3s


- name: Join K3s worker nodes
  hosts: k3s_agents
  become: true
  gather_facts: true

  roles:
    - k3s